import prisma from '../../src/config/prisma';
import request from 'supertest';
export { prisma };

export async function safeCleanupUsers(filter = 'test') {
  const testUsers = await prisma.user.findMany({
    where: { email: { contains: filter } },
    select: { id: true },
  });

  const userIds = testUsers.map((u) => u.id);
  if (!userIds.length) return;

  // Delete dependent records in order to avoid FK constraint errors
  const deleteIfExists = async (fn: () => Promise<any>) => {
    try {
      await fn();
    } catch (e) {
      // swallow - cleanup best-effort
    }
  };

  await deleteIfExists(() => prisma.ticket.deleteMany({ where: { userId: { in: userIds } } }));
  await deleteIfExists(() => prisma.order.deleteMany({ where: { userId: { in: userIds } } }));

  // Add other dependent deletes here if needed (sessions, refresh tokens, etc.)

  await deleteIfExists(() => prisma.user.deleteMany({ where: { id: { in: userIds } } }));
}

export async function registerUser(
  app: any,
  overrides: Partial<{
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    role: string;
  }> = {}
) {
  const defaultUser = {
    email: `test-${Date.now()}@example.com`,
    password: 'SecurePass123!',
    firstName: 'Test',
    lastName: 'User',
  };

  const userPayload = { ...defaultUser, ...overrides };
  const res = await request(app).post('/api/v1/auth/register').send(userPayload);
  if (!res.body || !res.body.data) {
    throw new Error(`Failed to register user: ${JSON.stringify(res.body)}`);
  }

  if (overrides.role && overrides.role !== 'CUSTOMER') {
    await prisma.user.update({
      where: { id: res.body.data.user.id },
      data: { role: overrides.role as any },
    });

    const loginRes = await request(app).post('/api/v1/auth/login').send({
      email: userPayload.email,
      password: userPayload.password,
    });

    if (!loginRes.body || !loginRes.body.data) {
      throw new Error(`Failed to login promoted user: ${JSON.stringify(loginRes.body)}`);
    }

    return loginRes.body.data;
  }

  return res.body.data; // { user, accessToken, refreshToken }
}

// New helpers: createOrganization, createVenue, createEvent, createOrder
export async function createOrganization(
  _app: any,
  _authToken: string,
  payload: Partial<{ name: string; slug: string; type: string; contactEmail: string }> = {}
) {
  const now = Date.now();
  return prisma.organization.create({
    data: {
      name: payload.name ?? `Org ${now}`,
      slug: payload.slug ?? `org-${now}`,
      type: (payload.type as any) ?? 'PROMOTER',
      status: 'ACTIVE',
    },
  });
}

export async function createVenue(
  _app: any,
  _authToken: string,
  payload: Partial<{ organizationId: string; name: string; address: any; capacity: number }> = {}
) {
  return prisma.venue.create({
    data: {
      organizationId: payload.organizationId!,
      name: payload.name ?? `Venue ${Date.now()}`,
      address: payload.address ?? {
        street: '1 Test St',
        city: 'Test City',
        state: 'TS',
        country: 'USA',
        postalCode: '00000',
      },
      capacity: payload.capacity ?? 100,
      timezone: 'UTC',
    },
  });
}

export async function createEvent(
  _app: any,
  _authToken: string,
  payload: Partial<{
    organizationId: string;
    venueId: string;
    title: string;
    description: string;
    startDateTime: string;
    endDateTime: string;
    status: string;
    capacity: number;
  }> = {}
) {
  const now = Date.now();
  return prisma.event.create({
    data: {
      organizationId: payload.organizationId!,
      venueId: payload.venueId ?? null,
      name: payload.title ?? `Event ${now}`,
      slug: `event-${now}-${Math.floor(Math.random() * 100000)}`,
      description: payload.description ?? 'Generated by testUtils',
      startDatetime: payload.startDateTime
        ? new Date(payload.startDateTime)
        : new Date(now + 24 * 60 * 60 * 1000),
      endDatetime: payload.endDateTime
        ? new Date(payload.endDateTime)
        : new Date(now + 26 * 60 * 60 * 1000),
      status: (payload.status as any) ?? 'DRAFT',
      capacity: payload.capacity ?? 1000,
      timezone: 'UTC',
      tags: [],
    },
  });
}

export async function createTicketType(
  app: any,
  authToken: string,
  payload: Partial<{
    eventId: string;
    name: string;
    price: number;
    quantity: number;
    maxPerOrder: number;
  }> = {}
) {
  const body = {
    eventId: payload.eventId,
    name: payload.name ?? 'General Admission',
    price: payload.price ?? 10.0,
    quantity: payload.quantity ?? 10,
    maxPerOrder: payload.maxPerOrder ?? 5,
  };

  const res = await request(app)
    .post('/api/v1/ticket-types')
    .set('Authorization', `Bearer ${authToken}`)
    .send(body);

  if (!res.body || !res.body.data)
    throw new Error(`Failed to create ticket type: ${JSON.stringify(res.body)}`);
  return res.body.data;
}

export async function createOrder(
  app: any,
  authToken: string,
  payload: Partial<{ items: Array<{ ticketTypeId: string; quantity: number }> }> = {}
) {
  const body = {
    items: payload.items ?? [],
  };

  const res = await request(app)
    .post('/api/v1/orders')
    .set('Authorization', `Bearer ${authToken}`)
    .send(body);

  if (!res.body || !res.body.data)
    throw new Error(`Failed to create order: ${JSON.stringify(res.body)}`);
  return res.body.data; // order object
}

// Cleanup helper to remove test data in the correct order
export async function cleanupTestData() {
  // Order of deletion matters because of foreign keys
  // 1. Child tables (ScanLog, Scanner, Notification, etc.)
  try {
    await prisma.scanLog.deleteMany();
  } catch (e) { }
  try {
    await prisma.scanner.deleteMany();
  } catch (e) { }
  try {
    await prisma.notification.deleteMany();
  } catch (e) { }
  try {
    await prisma.notificationPreference.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalComment.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalReviewDecision.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalReminder.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalReviewer.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalAsset.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalRevision.deleteMany();
  } catch (e) { }

  // 2. Transactional data (Ticket, Order)
  try {
    await prisma.waitlist.deleteMany();
  } catch (e) { }
  try {
    await prisma.taskComment.deleteMany();
  } catch (e) { }
  try {
    await prisma.task.deleteMany();
  } catch (e) { }
  try {
    await prisma.ticket.deleteMany();
  } catch (e) { }
  try {
    await prisma.order.deleteMany();
  } catch (e) { }

  // 3. Event related
  try {
    await prisma.ticketType.deleteMany();
  } catch (e) { }
  try {
    await prisma.approvalRequest.deleteMany();
  } catch (e) { }
  try {
    await prisma.event.deleteMany();
  } catch (e) { }

  // 4. Organization related
  try {
    await prisma.venue.deleteMany();
  } catch (e) { }
  try {
    await prisma.promoCode.deleteMany();
  } catch (e) { }

  // 5. Core entities (User, Organization)
  try {
    await prisma.user.deleteMany();
  } catch (e) { }
  try {
    await prisma.organization.deleteMany();
  } catch (e) { }
}
