import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'TixMo API',
      version: '0.1.0',
      description: 'Enterprise-grade ticket vendor platform API for event promoters',
      contact: {
        name: 'TixMo Team',
        email: 'api@tixmo.com',
      },
      license: {
        name: 'Proprietary',
      },
    },
    servers: [
      {
        url: 'http://localhost:3000/api/v1',
        description: 'Development server',
      },
      {
        url: 'https://api.tixmo.com/v1',
        description: 'Production server (future)',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Enter your JWT access token',
        },
      },
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid', description: 'User ID' },
            email: { type: 'string', format: 'email', description: 'User email address' },
            firstName: { type: 'string', description: 'User first name' },
            lastName: { type: 'string', description: 'User last name' },
            phone: { type: 'string', nullable: true, description: 'User phone number' },
            role: {
              type: 'string',
              enum: ['ADMIN', 'PROMOTER', 'CUSTOMER', 'SCANNER'],
              description: 'User role',
            },
            organizationId: {
              type: 'string',
              format: 'uuid',
              nullable: true,
              description: 'Organization ID (for promoters)',
            },
            emailVerified: { type: 'boolean', description: 'Email verification status' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Error: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string' },
            statusCode: { type: 'number' },
            errors: { type: 'object', description: 'Validation errors (if any)' },
          },
        },
        // Enums
        OrganizationType: {
          type: 'string',
          enum: ['PROMOTER', 'VENUE', 'RESELLER'],
        },
        OrganizationStatus: {
          type: 'string',
          enum: ['ACTIVE', 'SUSPENDED', 'PENDING'],
        },
        EventStatus: {
          type: 'string',
          enum: ['DRAFT', 'PUBLISHED', 'ON_SALE', 'SOLD_OUT', 'CANCELLED', 'COMPLETED'],
        },
        TicketTypeStatus: {
          type: 'string',
          enum: ['ACTIVE', 'SOLD_OUT', 'HIDDEN'],
        },
        OrderStatus: {
          type: 'string',
          enum: ['PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED'],
        },
        PaymentStatus: {
          type: 'string',
          enum: ['PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED'],
        },
        TicketStatus: {
          type: 'string',
          enum: ['VALID', 'USED', 'CANCELLED', 'TRANSFERRED'],
        },
        DiscountType: {
          type: 'string',
          enum: ['PERCENTAGE', 'FIXED_AMOUNT'],
        },
        PromoCodeStatus: {
          type: 'string',
          enum: ['ACTIVE', 'EXPIRED', 'DISABLED'],
        },
        ScannerStatus: {
          type: 'string',
          enum: ['ACTIVE', 'DISABLED', 'REVOKED'],
        },
        NotificationType: {
          type: 'string',
          enum: [
            'ORDER_CONFIRMATION',
            'TICKET_TRANSFER',
            'EVENT_REMINDER',
            'WELCOME',
            'PROMO',
            'ANNOUNCEMENT',
          ],
        },
        NotificationStatus: {
          type: 'string',
          enum: ['PENDING', 'SENT', 'FAILED', 'READ'],
        },
        // Core domain models
        Organization: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            slug: { type: 'string' },
            type: { $ref: '#/components/schemas/OrganizationType' },
            stripeAccountId: { type: 'string', nullable: true },
            status: { $ref: '#/components/schemas/OrganizationStatus' },
            settings: { type: 'object', nullable: true, additionalProperties: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Venue: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            organizationId: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            address: { type: 'object', additionalProperties: true },
            capacity: { type: 'integer' },
            seatingChart: { type: 'object', nullable: true, additionalProperties: true },
            timezone: { type: 'string' },
            metadata: { type: 'object', nullable: true, additionalProperties: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Event: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            organizationId: { type: 'string', format: 'uuid' },
            venueId: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            slug: { type: 'string' },
            description: { type: 'string', nullable: true },
            category: { type: 'string' },
            tags: { type: 'array', items: { type: 'string' } },
            startDatetime: { type: 'string', format: 'date-time' },
            endDatetime: { type: 'string', format: 'date-time' },
            timezone: { type: 'string' },
            status: { $ref: '#/components/schemas/EventStatus' },
            images: { type: 'object', nullable: true, additionalProperties: true },
            metadata: { type: 'object', nullable: true, additionalProperties: true },
            salesStart: { type: 'string', format: 'date-time', nullable: true },
            salesEnd: { type: 'string', format: 'date-time', nullable: true },
            capacity: { type: 'integer' },
            minTicketPrice: { type: 'string', nullable: true, description: 'Decimal string' },
            maxTicketPrice: { type: 'string', nullable: true, description: 'Decimal string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        TicketType: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            eventId: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            description: { type: 'string', nullable: true },
            price: { type: 'string', description: 'Decimal string' },
            quantityTotal: { type: 'integer' },
            quantityAvailable: { type: 'integer' },
            quantitySold: { type: 'integer' },
            quantityHeld: { type: 'integer' },
            salesStart: { type: 'string', format: 'date-time', nullable: true },
            salesEnd: { type: 'string', format: 'date-time', nullable: true },
            maxPerOrder: { type: 'integer' },
            requiresSeatSelection: { type: 'boolean' },
            metadata: { type: 'object', nullable: true, additionalProperties: true },
            status: { $ref: '#/components/schemas/TicketTypeStatus' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Order: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            orderNumber: { type: 'string' },
            userId: { type: 'string', format: 'uuid' },
            eventId: { type: 'string', format: 'uuid' },
            status: { $ref: '#/components/schemas/OrderStatus' },
            totalAmount: { type: 'string', description: 'Decimal string' },
            feesAmount: { type: 'string', description: 'Decimal string' },
            taxAmount: { type: 'string', description: 'Decimal string' },
            discountAmount: { type: 'string', description: 'Decimal string' },
            paymentStatus: { $ref: '#/components/schemas/PaymentStatus' },
            paymentIntentId: { type: 'string', nullable: true },
            paymentMethod: { type: 'string', nullable: true },
            promoCodeId: { type: 'string', format: 'uuid', nullable: true },
            ipAddress: { type: 'string', nullable: true },
            userAgent: { type: 'string', nullable: true },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Ticket: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            orderId: { type: 'string', format: 'uuid' },
            eventId: { type: 'string', format: 'uuid' },
            ticketTypeId: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            barcode: { type: 'string' },
            qrCodeUrl: { type: 'string', nullable: true },
            seatInfo: { type: 'object', nullable: true, additionalProperties: true },
            status: { $ref: '#/components/schemas/TicketStatus' },
            pricePaid: { type: 'string', description: 'Decimal string' },
            checkedInAt: { type: 'string', format: 'date-time', nullable: true },
            checkedInBy: { type: 'string', nullable: true },
            transferredFrom: { type: 'string', nullable: true },
            transferredAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        PromoCode: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            organizationId: { type: 'string', format: 'uuid' },
            code: { type: 'string' },
            description: { type: 'string', nullable: true },
            discountType: { $ref: '#/components/schemas/DiscountType' },
            discountValue: { type: 'string', description: 'Decimal string' },
            maxUses: { type: 'integer', nullable: true },
            usesCount: { type: 'integer' },
            validFrom: { type: 'string', format: 'date-time' },
            validUntil: { type: 'string', format: 'date-time' },
            applicableEvents: { type: 'array', items: { type: 'string', format: 'uuid' } },
            minOrderValue: { type: 'string', nullable: true, description: 'Decimal string' },
            status: { $ref: '#/components/schemas/PromoCodeStatus' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Scanner: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            deviceId: { type: 'string', nullable: true },
            apiKey: { type: 'string' },
            organizationId: { type: 'string', format: 'uuid' },
            eventId: { type: 'string', format: 'uuid', nullable: true },
            createdBy: { type: 'string' },
            status: { $ref: '#/components/schemas/ScannerStatus' },
            lastUsedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ScanLog: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            scannerId: { type: 'string', format: 'uuid' },
            ticketId: { type: 'string', format: 'uuid' },
            eventId: { type: 'string', format: 'uuid' },
            scanType: { type: 'string', enum: ['ENTRY', 'EXIT', 'VALIDATION'] },
            success: { type: 'boolean' },
            failureReason: { type: 'string', nullable: true },
            metadata: { type: 'object', nullable: true, additionalProperties: true },
            scannedAt: { type: 'string', format: 'date-time' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            type: { $ref: '#/components/schemas/NotificationType' },
            status: { $ref: '#/components/schemas/NotificationStatus' },
            subject: { type: 'string' },
            message: { type: 'string' },
            metadata: { type: 'object', nullable: true, additionalProperties: true },
            sentAt: { type: 'string', format: 'date-time', nullable: true },
            readAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Waitlist: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            eventId: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            status: { type: 'string', enum: ['PENDING', 'NOTIFIED', 'EXPIRED', 'PURCHASED'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        NotificationPreference: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            emailOrderConfirm: { type: 'boolean' },
            emailTicketTransfer: { type: 'boolean' },
            emailEventReminder: { type: 'boolean' },
            emailPromo: { type: 'boolean' },
            emailAnnouncement: { type: 'boolean' },
            smsOrderConfirm: { type: 'boolean' },
            smsEventReminder: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Task: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            organizationId: { type: 'string', format: 'uuid' },
            assigneeId: { type: 'string', format: 'uuid', nullable: true },
            title: { type: 'string' },
            description: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['TO_DO', 'IN_PROGRESS', 'REVIEW', 'DONE'] },
            priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH'] },
            tag: { type: 'string', enum: ['DESIGN', 'LEGAL', 'GENERAL', 'OPS', 'MARKETING', 'DEV'], nullable: true },
            attachments: { type: 'array', items: { type: 'object' }, nullable: true },
            dueDate: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            comments: { type: 'array', items: { $ref: '#/components/schemas/TaskComment' } },
          }
        },
        TaskInput: {
          type: 'object',
          required: ['title'],
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            status: { type: 'string', enum: ['TO_DO', 'IN_PROGRESS', 'REVIEW', 'DONE'] },
            priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH'] },
            tag: { type: 'string', enum: ['DESIGN', 'LEGAL', 'GENERAL', 'OPS', 'MARKETING', 'DEV'] },
            assigneeId: { type: 'string', format: 'uuid' },
            dueDate: { type: 'string', format: 'date-time' },
            attachments: { type: 'array', items: { type: 'object' } }
          }
        },
        TaskComment: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            taskId: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            content: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            user: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid' },
                firstName: { type: 'string' },
                lastName: { type: 'string' }
              }
            }
          }
        },
        // Common patterns
        PaginationMeta: {
          type: 'object',
          properties: {
            page: { type: 'integer', minimum: 1 },
            limit: { type: 'integer', minimum: 1 },
            total: { type: 'integer', minimum: 0 },
            pages: { type: 'integer', minimum: 0 },
          },
        },
        IdParam: {
          type: 'object',
          properties: { id: { type: 'string', format: 'uuid' } },
          required: ['id'],
        },
      },
    },
    tags: [
      { name: 'Authentication', description: 'User authentication and authorization endpoints' },
      { name: 'Users', description: 'User management endpoints' },
      { name: 'Organizations', description: 'Organization management endpoints' },
      { name: 'Venues', description: 'Venue management endpoints' },
      { name: 'Events', description: 'Event management endpoints' },
      { name: 'Ticket Types', description: 'Ticket type and pricing management endpoints' },
      { name: 'Orders', description: 'Order and purchase management endpoints' },
      { name: 'Tickets', description: 'Ticket management and check-in endpoints' },
      { name: 'Promo Codes', description: 'Promotional discount code management endpoints' },
      { name: 'Scanners', description: 'Scanner device and ticket scanning endpoints' },
      { name: 'Notifications', description: 'User notifications and preferences endpoints' },
      { name: 'Analytics', description: 'Business analytics and reporting endpoints' },
      { name: 'Waitlists', description: 'Waitlist management for sold-out events' },
      { name: 'Health', description: 'Health check endpoints' },
    ],
  },
  apis: ['./src/api/**/*.ts', './src/app.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
